"""add email to user

Revision ID: 13b266f94e85
Revises: cf5d89475806
Create Date: 2026-05-18 10:46:49.947781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b266f94e85'
down_revision: Union[str, Sequence[str], None] = 'cf5d89475806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Используем batch mode для совместимости с SQLite
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint('uq_user_email', ['email'])

# def downgrade():
#     with op.batch_alter_table('user', schema=None) as batch_op:
#         batch_op.drop_constraint('uq_user_email', type_='unique')
#         batch_op.drop_column('email')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
