"""extend payment model

Revision ID: cf5d89475806
Revises: 1d3807dbeb42
Create Date: 2026-05-18 03:27:41.839120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5d89475806'
down_revision: Union[str, Sequence[str], None] = '1d3807dbeb42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_method', sa.String(length=30), nullable=True))
    op.add_column('payments', sa.Column('card_last4', sa.String(length=4), nullable=True))
    op.add_column('payments', sa.Column('description', sa.String(length=200), nullable=True))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'description')
    op.drop_column('payments', 'card_last4')
    op.drop_column('payments', 'payment_method')
    # ### end Alembic commands ###
